"""Test MV and CM comics pages layout and functionality."""
import sys, os, json, time
sys.path.insert(0, os.path.expanduser('~/.agents/skills/webapp-testing'))
from playwright.sync_api import sync_playwright

BASE = 'http://127.0.0.1:5050'

def test_comics_pages():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        ctx = browser.new_context(viewport={'width': 1280, 'height': 900})
        page = ctx.new_page()

        errors = []
        page.on('console', lambda msg: errors.append(('[ERR]' if msg.type == 'error' else '[WARN]', msg.text)))

        # Navigate to login page and submit the form
        page.goto(f'{BASE}/login')
        page.wait_for_load_state('networkidle')

        # Find form fields
        username_input = page.locator('#username').first
        password_input = page.locator('#password').first
        
        if username_input.count() > 0:
            username_input.fill('testuser')
        if password_input.count() > 0:
            password_input.fill('1234')
        
        # Find submit button
        submit_btn = page.locator('button[type="submit"]').first
        if submit_btn.count() > 0:
            submit_btn.click()
            page.wait_for_timeout(2000)
            print(f"After login URL: {page.url}")
        else:
            page.keyboard.press('Enter')
            page.wait_for_timeout(2000)
            print(f"After Enter URL: {page.url}")

        # ─── MV comics page ───
        print("\n=== MV comics ===")
        page.goto(f'{BASE}/mediavault/comics')
        page.wait_for_load_state('networkidle')
        page.wait_for_timeout(500)

        page.screenshot(path='/tmp/mv_comics.png', full_page=True)
        print(f"URL: {page.url}")

        cards = page.locator('.cm-comic-card, .cm-comics-grid > *')
        card_count = cards.count()
        print(f"Cards found: {card_count}")

        # Card dimensions — check all cards
        cards = page.locator('.cm-comic-card')
        card_count = cards.count()
        print(f"Cards found: {card_count}")
        if card_count > 0:
            widths = set()
            for i in range(card_count):
                box = cards.nth(i).bounding_box()
                widths.add(round(box['width']))
                print(f"  Card {i+1}: x={box['x']:.0f} y={box['y']:.0f} w={box['width']:.0f} h={box['height']:.0f}")
            if len(widths) > 1:
                print(f"  WARNING: cards have different widths: {sorted(widths)}")
            else:
                print(f"  All cards same width: {widths}")

        # Check grid layout
        grid = page.locator('.cm-comics-grid, #comicsGrid')
        if grid.count() > 0:
            gbox = grid.first.bounding_box()
            print(f"Grid: x={gbox['x']:.0f} y={gbox['y']:.0f} w={gbox['width']:.0f} h={gbox['height']:.0f}")

        # ─── CM comics-edit page ───
        print("\n=== CM comics-edit ===")
        page.goto(f'{BASE}/content-mgmt/comics-edit')
        page.wait_for_load_state('networkidle')
        page.wait_for_timeout(500)

        page.screenshot(path='/tmp/cm_comics.png', full_page=True)
        print(f"URL: {page.url}")

        cards2 = page.locator('.cm-comic-card, .cm-comics-grid > *')
        card_count2 = cards2.count()
        print(f"Cards found: {card_count2}")

        # Check ComicsPicker
        has_picker = page.evaluate('typeof ComicsPicker !== "undefined"')
        print(f"ComicsPicker defined: {has_picker}")
        has_cm_bridge = page.evaluate('typeof window.ComicsPicker !== "undefined"')
        print(f"window.ComicsPicker: {has_cm_bridge}")

        if card_count2 > 0:
            first2 = cards2.first
            box2 = first2.bounding_box()
            print(f"First card: x={box2['x']:.0f} y={box2['y']:.0f} w={box2['width']:.0f} h={box2['height']:.0f}")
            if box2['width'] > 500:
                print(f"  WARNING: card too wide ({box2['width']:.0f}px)")

        # Check for cmContentBody
        ccb = page.locator('#cmContentBody')
        print(f"#cmContentBody exists: {ccb.count() > 0}")
        if ccb.count() > 0:
            ccb_box = ccb.bounding_box()
            print(f"  #cmContentBody: w={ccb_box['width']:.0f} h={ccb_box['height']:.0f}")

        # Check #cmComics (generated by content/comics.js)
        cm_comics = page.locator('#cmComics')
        print(f"#cmComics exists: {cm_comics.count() > 0}")
        if cm_comics.count() > 0:
            cc_box = cm_comics.bounding_box()
            print(f"  #cmComics: w={cc_box['width']:.0f} h={cc_box['height']:.0f}")

        # Log errors
        if errors:
            print(f"\nConsole errors ({len(errors)}):")
            for level, msg in errors[:10]:
                print(f"  {level} {msg[:200]}")

        browser.close()
        print("\nDone")

if __name__ == '__main__':
    test_comics_pages()
